import { Button, CheckBox, ComboBox, TextEdit, Palette } from "std-widgets.slint";
import { Rt-Sa-Wc-ComboBox } from "rt-sa-wc.slint";
import { Word-Box } from "word-box.slint";

export global guiGlobals {
    in property <string> device;
    in property <int> rt;
    in property <int> sa;
    in property <int> wc;
    in property <string> bus;
    in property <[string]> words;
}

export component AppWindow inherits Window {
    min-width: 700px;
    preferred-width: 700px;

    min-height: 400px;
    preferred-height: 400px;

    property <int> commandType: 0; // Bc->RT: 0, RT->BC:1, RT->RT:2
    callback connectPressed();
    callback sendPressed(int);

    public function setError(errorMsg: string) {
        errorText.color = Colors.red;
        errorText.text = errorMsg;
    }

    public function setStatus(statusMsg: string) {
        errorText.color = Colors.green;
        errorText.text = statusMsg;
    }

    public function setTime(time: string) {
        timeText.text = time;
    }

    init => {
        Palette.color-scheme = ColorScheme.dark;
    }

    VerticalLayout {
        HorizontalLayout {
            HorizontalLayout {
                padding: 25px;
                spacing: 10px;
                alignment: start;

                Text {
                    text: "Device#: ";
                    font-size: 15px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                device-box := Word-Box {
                    text: "0000";
                }

                Button {
                    text: "Connect";
                    primary: true;
                    clicked => {
                        guiGlobals.device = device-box.text;
                        connectPressed();
                    }
                }
            }

            HorizontalLayout {
                padding: 25px;
                alignment: end;

                bcToRtCheckBox := CheckBox {
                    text: "BC to RT";
                    checked: true;
                    toggled => {
                        rtToBcCheckBox.checked = !self.checked;

                        if (bcToRtCheckBox.checked) {
                            commandType = 0;
                        }
                    }
                }

                rtToBcCheckBox := CheckBox {
                    text: "RT to BC";
                    toggled => {
                        bcToRtCheckBox.checked = !self.checked;

                        if (rtToBcCheckBox.checked) {
                            commandType = 1;
                        }
                    }
                }

                Button {
                    text: "Send";
                    primary: true;
                    clicked => {
                        guiGlobals.bus = busComboBox.current-value;
                        guiGlobals.rt = rt-ComboBox.current-value.to-float();
                        guiGlobals.sa = sa-ComboBox.current-value.to-float();
                        guiGlobals.wc = wc-ComboBox.current-value.to-float();
                        guiGlobals.words = [
                            "0x" + word0.text,
                            "0x" + word1.text,
                            "0x" + word2.text,
                            "0x" + word3.text,
                            "0x" + word4.text,
                            "0x" + word5.text,
                            "0x" + word6.text,
                            "0x" + word7.text,
                            "0x" + word8.text,
                            "0x" + word9.text,
                            "0x" + word10.text,
                            "0x" + word11.text,
                            "0x" + word12.text,
                            "0x" + word13.text,
                            "0x" + word14.text,
                            "0x" + word15.text,
                            "0x" + word16.text,
                            "0x" + word17.text,
                            "0x" + word18.text,
                            "0x" + word19.text,
                            "0x" + word20.text,
                            "0x" + word21.text,
                            "0x" + word22.text,
                            "0x" + word23.text,
                            "0x" + word24.text,
                            "0x" + word25.text,
                            "0x" + word26.text,
                            "0x" + word27.text,
                            "0x" + word28.text,
                            "0x" + word29.text,
                            "0x" + word30.text,
                            "0x" + word31.text
                        ];
                        sendPressed(commandType);
                    }
                }
            }
        }

        HorizontalLayout {
            padding: 25px;
            alignment: center;

            Text {
                text: "Bus: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            busComboBox := ComboBox {
                current-value: "A";
                width: 75px;
                model: ["A", "B"];
            }

            Text {
                text: "  RT: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            rt-ComboBox := Rt-Sa-Wc-ComboBox { }

            Text {
                text: "  SA: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            sa-ComboBox := Rt-Sa-Wc-ComboBox { }

            Text {
                text: "  WC: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            wc-ComboBox := Rt-Sa-Wc-ComboBox { }
        }

        GridLayout {
            padding: 15px;
            spacing: 15px;
            Row {
                word0 := Word-Box {
                    text: "0000";
                }

                word1 := Word-Box {
                    text: "1111";
                }

                word2 := Word-Box {
                    text: "2222";
                }

                word3 := Word-Box {
                    text: "3333";
                }

                word4 := Word-Box {
                    text: "4444";
                }

                word5 := Word-Box {
                    text: "5555";
                }

                word6 := Word-Box {
                    text: "6666";
                }

                word7 := Word-Box {
                    text: "7777";
                }
            }

            Row {
                word8 := Word-Box {
                    text: "8888";
                }

                word9 := Word-Box {
                    text: "9999";
                }

                word10 := Word-Box {
                    text: "AAAA";
                }

                word11 := Word-Box {
                    text: "BBBB";
                }

                word12 := Word-Box {
                    text: "CCCC";
                }

                word13 := Word-Box {
                    text: "DDDD";
                }

                word14 := Word-Box {
                    text: "EEEE";
                }

                word15 := Word-Box {
                    text: "FFFF";
                }
            }

            Row {
                word16 := Word-Box {
                    text: "0001";
                }

                word17 := Word-Box {
                    text: "0002";
                }

                word18 := Word-Box {
                    text: "0004";
                }

                word19 := Word-Box {
                    text: "0008";
                }

                word20 := Word-Box {
                    text: "0010";
                }

                word21 := Word-Box {
                    text: "0020";
                }

                word22 := Word-Box {
                    text: "0040";
                }

                word23 := Word-Box {
                    text: "0080";
                }
            }

            Row {
                word24 := Word-Box {
                    text: "0100";
                }

                word25 := Word-Box {
                    text: "0200";
                }

                word26 := Word-Box {
                    text: "0400";
                }

                word27 := Word-Box {
                    text: "0800";
                }

                word28 := Word-Box {
                    text: "1000";
                }

                word29 := Word-Box {
                    text: "2000";
                }

                word30 := Word-Box {
                    text: "4000";
                }

                word31 := Word-Box {
                    text: "8000";
                }
            }
        }

        HorizontalLayout {
            height: 20px;
            padding-left: 10px;
            padding-right: 10px;

            errorText := Text {
                color: green;
            }

            timeText := Text {
                horizontal-alignment: right;
                text: "0";
            }
        }
    }
}
