import { Button, CheckBox, ComboBox, TextEdit, Palette } from "std-widgets.slint";
import { Rt-Sa-Wc-ComboBox } from "rt-sa-wc.slint";
import { Word-Box } from "word-box.slint";
import { ConfigFileWindow } from "config-file-window.slint";

export global guiGlobals {
    in property <string> device;
    in property <bool> is-repeat: false;
    in property <int> rt;
    in property <int> sa;
    in property <int> rt-rx;
    in property <int> sa-rx;
    in property <int> wc;
    in property <string> bus;
    in property <[string]> words;
    in property <int> bcMode; // Bc->RT: 0, RT->BC:1, RT->RT:2
}

export component AppWindow inherits Window {
    title: "MIL-STD-1553 Bus Controller";

    min-width: 800px;
    min-height: 400px;

    callback connectPressed();
    callback sendPressed(int);
    callback stopPressed <=> config-file-window.stopRun;

    callback browseConfig <=> config-file-window.browseConfig;
    callback startConfigRun <=> config-file-window.startConfigRun;
    callback setConfigPath <=> config-file-window.setConfigPath;

    public function setError(errorMsg: string) {
        errorText.color = Colors.red;
        errorText.text = errorMsg;
    }

    public function setConnectStatus(status: bool) {
        if (status) {
            errorText.color = Colors.green;
            errorText.text = "Connected to device " + guiGlobals.device;
            sendButton.enabled = true;
            runConfigButton.enabled = true;
        } else {
            // Failure status message set by setError
            sendButton.enabled = false;
            runConfigButton.enabled = false;
        }
    }

    public function setUiFromConfig() {
        device-box.text = guiGlobals.device;

        busComboBox.current-value = guiGlobals.bus;
        rt-ComboBox.current-value = guiGlobals.rt;
        sa-ComboBox.current-value = guiGlobals.sa;
        wc-ComboBox.current-value = guiGlobals.wc;
        rt-ComboBox-2.current-value = guiGlobals.rt-rx;
        sa-ComboBox-2.current-value = guiGlobals.sa-rx;

        bcModeCombo.current-index = guiGlobals.bcMode; // FIXME: bug if index is 2
        busModeComboHandler();

        word0.text = guiGlobals.words[0];
        word1.text = guiGlobals.words[1];
        word2.text = guiGlobals.words[2];
        word3.text = guiGlobals.words[3];
        word4.text = guiGlobals.words[4];
        word5.text = guiGlobals.words[5];
        word6.text = guiGlobals.words[6];
        word7.text = guiGlobals.words[7];
        word8.text = guiGlobals.words[8];
        word9.text = guiGlobals.words[9];
        word10.text = guiGlobals.words[10];
        word11.text = guiGlobals.words[11];
        word12.text = guiGlobals.words[12];
        word13.text = guiGlobals.words[13];
        word14.text = guiGlobals.words[14];
        word15.text = guiGlobals.words[15];
        word16.text = guiGlobals.words[16];
        word17.text = guiGlobals.words[17];
        word18.text = guiGlobals.words[18];
        word19.text = guiGlobals.words[19];
        word20.text = guiGlobals.words[20];
        word21.text = guiGlobals.words[21];
        word22.text = guiGlobals.words[22];
        word23.text = guiGlobals.words[23];
        word24.text = guiGlobals.words[24];
        word25.text = guiGlobals.words[25];
        word26.text = guiGlobals.words[26];
        word27.text = guiGlobals.words[27];
        word28.text = guiGlobals.words[28];
        word29.text = guiGlobals.words[29];
        word30.text = guiGlobals.words[30];
        word31.text = guiGlobals.words[31];
    }

    function busModeComboHandler() {
        guiGlobals.bcMode = bcModeCombo.current-index;

        if (bcModeCombo.current-index == 2) {
            rt-text-1.text = "  RT Tx: ";
            sa-text-1.text = "  SA Tx: ";

            rx-rt-sa-layout.visible = true;
            root.height += 40px;
            rx-rt-sa-layout.height = 40px;
        } else {
            rt-text-1.text = "  RT: ";
            sa-text-1.text = "  SA: ";

            root.height -= rx-rt-sa-layout.height;
            rx-rt-sa-layout.height = 0px;
            rx-rt-sa-layout.visible = false;
        }
    }

    init => {
        Palette.color-scheme = ColorScheme.dark;
    }

    VerticalLayout {
        HorizontalLayout {
            HorizontalLayout {
                padding: 15px;
                spacing: 10px;
                alignment: start;

                Text {
                    text: "Device#: ";
                    font-size: 15px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                device-box := Word-Box {
                    width: 65px;
                    text: "0000";
                }

                Button {
                    text: "Connect";
                    primary: true;
                    clicked => {
                        guiGlobals.device = device-box.text;
                        connectPressed();
                    }
                }
            }

            HorizontalLayout {
                padding: 15px;
                spacing: 10px;
                alignment: end;

                runConfigButton := Button {
                    text: "Run from config";
                    primary: true;
                    enabled: false;
                    clicked => {
                        config-file-window.isActive = true;
                    }
                }

                Rectangle {
                    background: guiGlobals.is-repeat && repeat-toggle-touch.has-hover ? Palette.accent-background.darker(30%) : // on and hover
                    (guiGlobals.is-repeat && !repeat-toggle-touch.has-hover) ? Palette.accent-background : // on and no hover
                    (!guiGlobals.is-repeat && repeat-toggle-touch.has-hover) ? Palette.alternate-background.darker(-30%) : // off and hover
                    (!guiGlobals.is-repeat && !repeat-toggle-touch.has-hover) ? Palette.alternate-background : black; // off and no hover

                    width: 40px;
                    height: 40px;
                    border-radius: 10px;

                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: center;
                        height: 100%;
                        width: 100%;
                        text: "⟳";
                        font-size: 25px;
                        color: guiGlobals.is-repeat ? black : white;
                    }

                    repeat-toggle-touch := TouchArea {
                        clicked => {
                            guiGlobals.is-repeat = !guiGlobals.is-repeat;

                            if (!guiGlobals.is-repeat) {
                                stopPressed();
                            }
                        }
                    }
                }

                bcModeCombo := ComboBox {
                    current-value: "BC → RT";
                    width: 125px;
                    model: ["BC → RT", "RT → BC", "RT → RT"];
                    selected => {
                        busModeComboHandler();
                    }
                }

                sendButton := Button {
                    text: "Send";
                    primary: true;
                    enabled: false;
                    clicked => {
                        guiGlobals.bus = busComboBox.current-value;
                        guiGlobals.rt = rt-ComboBox.current-value.to-float();
                        guiGlobals.sa = sa-ComboBox.current-value.to-float();
                        guiGlobals.rt-rx = rt-ComboBox-2.current-value.to-float();
                        guiGlobals.sa-rx = sa-ComboBox-2.current-value.to-float();
                        guiGlobals.wc = wc-ComboBox.current-value.to-float();
                        guiGlobals.words = [
                            "0x" + word0.text,
                            "0x" + word1.text,
                            "0x" + word2.text,
                            "0x" + word3.text,
                            "0x" + word4.text,
                            "0x" + word5.text,
                            "0x" + word6.text,
                            "0x" + word7.text,
                            "0x" + word8.text,
                            "0x" + word9.text,
                            "0x" + word10.text,
                            "0x" + word11.text,
                            "0x" + word12.text,
                            "0x" + word13.text,
                            "0x" + word14.text,
                            "0x" + word15.text,
                            "0x" + word16.text,
                            "0x" + word17.text,
                            "0x" + word18.text,
                            "0x" + word19.text,
                            "0x" + word20.text,
                            "0x" + word21.text,
                            "0x" + word22.text,
                            "0x" + word23.text,
                            "0x" + word24.text,
                            "0x" + word25.text,
                            "0x" + word26.text,
                            "0x" + word27.text,
                            "0x" + word28.text,
                            "0x" + word29.text,
                            "0x" + word30.text,
                            "0x" + word31.text
                        ];
                        sendPressed(guiGlobals.bcMode);
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: center;

            config-file-window := ConfigFileWindow { }
        }

        HorizontalLayout {
            padding: 15px;
            alignment: center;
            visible: !config-file-window.isActive;

            Text {
                text: "Bus: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            busComboBox := ComboBox {
                current-value: "A";
                width: 75px;
                model: ["A", "B"];
            }

            rt-text-1 := Text {
                text: "  RT: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            rt-ComboBox := Rt-Sa-Wc-ComboBox { }

            sa-text-1 := Text {
                text: "  SA: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            sa-ComboBox := Rt-Sa-Wc-ComboBox { }

            Text {
                text: "  WC: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            wc-ComboBox := Rt-Sa-Wc-ComboBox { }
        }

        rx-rt-sa-layout := HorizontalLayout {
            alignment: center;
            padding-left: 3px;
            height: 0px;
            visible: false;

            animate height { duration: 300ms; }

            Text {
                text: "RT Rx: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            rt-ComboBox-2 := Rt-Sa-Wc-ComboBox { }

            Text {
                text: "  SA Rx: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            sa-ComboBox-2 := Rt-Sa-Wc-ComboBox { }
        }

        GridLayout {
            padding: 15px;
            spacing: 15px;
            visible: !config-file-window.isActive;

            Text {
                horizontal-alignment: left;
                vertical-alignment: bottom;
                text: "Data:";
                font-size: 20px;
            }

            Row {
                word0 := Word-Box {
                    text: "0000";
                }

                word1 := Word-Box {
                    text: "1111";
                }

                word2 := Word-Box {
                    text: "2222";
                }

                word3 := Word-Box {
                    text: "3333";
                }

                word4 := Word-Box {
                    text: "4444";
                }

                word5 := Word-Box {
                    text: "5555";
                }

                word6 := Word-Box {
                    text: "6666";
                }

                word7 := Word-Box {
                    text: "7777";
                }
            }

            Row {
                word8 := Word-Box {
                    text: "8888";
                }

                word9 := Word-Box {
                    text: "9999";
                }

                word10 := Word-Box {
                    text: "AAAA";
                }

                word11 := Word-Box {
                    text: "BBBB";
                }

                word12 := Word-Box {
                    text: "CCCC";
                }

                word13 := Word-Box {
                    text: "DDDD";
                }

                word14 := Word-Box {
                    text: "EEEE";
                }

                word15 := Word-Box {
                    text: "FFFF";
                }
            }

            Row {
                word16 := Word-Box {
                    text: "0001";
                }

                word17 := Word-Box {
                    text: "0002";
                }

                word18 := Word-Box {
                    text: "0004";
                }

                word19 := Word-Box {
                    text: "0008";
                }

                word20 := Word-Box {
                    text: "0010";
                }

                word21 := Word-Box {
                    text: "0020";
                }

                word22 := Word-Box {
                    text: "0040";
                }

                word23 := Word-Box {
                    text: "0080";
                }
            }

            Row {
                word24 := Word-Box {
                    text: "0100";
                }

                word25 := Word-Box {
                    text: "0200";
                }

                word26 := Word-Box {
                    text: "0400";
                }

                word27 := Word-Box {
                    text: "0800";
                }

                word28 := Word-Box {
                    text: "1000";
                }

                word29 := Word-Box {
                    text: "2000";
                }

                word30 := Word-Box {
                    text: "4000";
                }

                word31 := Word-Box {
                    text: "8000";
                }
            }
        }

        HorizontalLayout {
            height: 20px;
            padding-left: 10px;
            padding-right: 10px;

            errorText := Text {
                text: "Ready, press connect";
                color: green;
            }

            Text {
                horizontal-alignment: right;
                text: "v1.0";
            }
        }
    }
}
