import { Button, CheckBox, ComboBox } from "std-widgets.slint";

export global guiGlobals {
    in property <int> rt;
    in property <int> sa;
    in property <int> wc;
    in property <string> bus;
}

export component AppWindow inherits Window {
    preferred-width: 600px;
    preferred-height: 600px;

    property <int> commandType: 0; // Bc->RT: 0, RT->BC:1, RT->RT:2
    callback sendPressed(int);

    VerticalLayout {
        HorizontalLayout {
            bcToRtCheckBox := CheckBox {
                text: "BC to RT";
                checked: true;
                toggled => {
                    rtToBcCheckBox.checked = !self.checked;

                    if (bcToRtCheckBox.checked) {
                        commandType = 0;
                    }
                }
            }

            rtToBcCheckBox := CheckBox {
                text: "RT to BC";
                toggled => {
                    bcToRtCheckBox.checked = !self.checked;

                    if (rtToBcCheckBox.checked) {
                        commandType = 1;
                    }
                }
            }

            Button {
                text: "Send";
                clicked => {
                    sendPressed(commandType);
                }
            }
        }

        HorizontalLayout {
            height: 50px;

            Text {
                text: "Bus: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            busComboBox := ComboBox {
                current-value: "A";
                width: 75px;
                selected => {
                    guiGlobals.bus = self.current-value;
                }
                model: ["A", "B"];
            }

            Text {
                text: "RT: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            rtComboBox := ComboBox {
                current-value: "0";
                width: 75px;
                selected => {
                    guiGlobals.rt = self.current-value.to-float();
                }
                model: [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31
                ];
            }

            Text {
                text: "SA: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            saComboBox := ComboBox {
                current-value: "0";
                width: 75px;
                selected => {
                    guiGlobals.sa = self.current-value.to-float();
                }
                model: [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31
                ];
            }

            Text {
                text: "WC: ";
                font-size: 30px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            wcComboBox := ComboBox {
                current-value: "0";
                width: 75px;
                selected => {
                    guiGlobals.wc = self.current-value.to-float();
                }
                model: [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31
                ];
            }
        }
    }
}
