import { ComboBox } from "std-widgets.slint";

export component Rt-Sa-Wc-ComboBox inherits ComboBox {
    current-value: "0";
    height: 40px;
    width: 75px;
    model: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31
    ];
}